
services:

  postgres_db:
    image: postgres:latest
    container_name: postgres_container
    restart: always
    command: -p 5432
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file:
      - .env

  back:
    build: backend/
    ports:
      - 5431:5431
    depends_on:
      - postgres_db
    env_file:
      - .env

  adminer_app:
    image: adminer
    container_name: adminer_container
    user: '111'
    restart: always
    env_file:
      - .env
    depends_on:
      - postgres_db
    ports:
      - 8080:8080

volumes:
  pg_data:
